name: LuaCraft
version: 1.0
api-version: 1.21
main: org.dankfmemes.luacraft.LuaCraft
commands:
  runscript:
    description: Run a Lua script
    usage: /<command>
permissions:
  luacraft.runscript:
    description: Allows execution of Lua scripts
