name: LuaCraft
version: 1.1.2
api-version: 1.21
main: com.shawnjb.luacraft.LuaCraft
commands:
  loadscript:
    description: Load and execute a Lua script from the lua directory
    usage: /<command> <filename>
    permissions:
      luacraft.loadscript:
        description: Allows execution of Lua scripts by loading them from lua
  listscripts:
    description: List all available Lua scripts in the lua directory
    usage: /<command>
    permissions:
      luacraft.listscripts:
        description: Allows viewing of available Lua scripts
permissions:
  luacraft.loadscript:
    description: Allows execution of Lua scripts by loading them from lua
  luacraft.listscripts:
    description: Allows viewing of available Lua scripts
